FROM node:14

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .
COPY email-config.json .

EXPOSE 2000

CMD ["node", "server.js"]
