version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - $HOME/ssl:/etc/nginx/ssl:ro
    depends_on:
      - nodejs
    restart: unless-stopped
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "2000:2000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
networks:
  default:
    driver: bridge
