version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "2000:2000"

networks:
  default:
    driver: bridge
